travis:
  secure:
    BINSTAR_TOKEN: cAcssJ2lehUMaT9Rt4PhNigqK/dBeMi5OUJAs3vyeUZvK5VavtsjHxGHNeUdjpzF3gWMkfWHjKoew5JQuZN+ucggaDreNRxi/vri1vKSS/e8dPCoyf76SKw3AbRX8cKihgX7f9rn+sw4pf/IZ+5EOEsWVzvFeEdSuEMaQU3FYJbvlL86yDqgGzLWHaFZYdQ5ZGa/g51IOhnC0RWbbVceEMaRtjP8Nje5srcz9QXi4PzF25W6hvcuux8M1OIsN0Jn1K6SzTcL00hsK9qfeGeZ0O/2enD5z4MT0Vy66cAqI4qszG50cHEHj5JZNdUNU2WmcIDDIG5vxl4LX3bIqmbPzgleElyF9c0aj0j9kXaMffdZazP2am5wC8qNLkFB5EyU7oRb9Lr2XRDHjHmpnK+7cqSxjMQawWNo966823GMDTvp/kxX9/4mhSze5v/tGXF4ESv+XMZ16CgBjoy0HfO3saog2d0Lz0FGaf995vlfbDWZx9U/0NeYHNekH1u0oZuc+ZvA+oH0QzjNGuQuXMzNQoik8v2Jf/X6JT+eLZZPb4gMXf7SsRK3xbF1mqDCMAgRHfufFcZAEoWK6cUpe6d1ndWZjI8l9GFjeQmt8ZxqdUZqXYGKITcOxvobtD5CIuwGjCVpIrmavH5Jp2TQYyegjFCzfVEXwd8Ma5miuY63Oc0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
